### DISCUSSION TITLE
Validator 2.0

### DISCUSSION THREAD

**Discussion by Coffee2Bits** [DevOps-MBSE/AaC#125] [Archive] [answered]
Proposal for a new validation approach. This proposal addresses two primary goals:
1. define validation rules in the AaC DSL 2.0
2. address structural gaps in the current validation approach

The general idea will be to define validation of AaC DSL structures in the DSL and supply validators, following the plugin architecture, to programmatically execute the validation defined in the DSL, similarly to how Cucumber/Gherkin step definitions are mapped to and used to execute human-language instructions programmatically.

### Defining Validation in the DSL

In order to define validation in the DSL, we’ll need to implement a method similar to how Gherkin implements test steps by tying human language instructions to a module that can programmatically perform the test, or validation in our case.

Here’s an example where we define 3 validation rules: 
1. Validation instructions must have an accompanying validator module
2. Required fields must be present
3.  Extensions must define one and only one of either enumExt or dataExt:

```yaml
---
ext:
  name: validation
  add:
    - name: text
      type: string
    - name: arguments
      type: string[]
  required:
    - text
  validation:
    - text: Every validation definition must have a corresponding validator module
---
data:
  name: data
  fields:
    - name: name
      type: string
    - name: fields
      type: Field[]
    - name: required
      type: string[]
  required:
    - name
    - fields
  validation:
    - text: Every field in the required attribute must be defined
---
data:
  name: extension
  fields:
    - name: name
      type: string
    - name: type
      type: string
    - name: enumExt
      type: EnumExtension
    - name: dataExt
      type: DataExtension
  required:
    - name
    - type
  validation:
    - text: One and only one field must be defined
      arguments:
        - enumExt
        - dataExt
```

In order to facilitate this linking of validation human instructions to validation modules, modules will need to expose the human instructions that it relates to. We will explore that more in the Validation Modules section below.

### Structure-level Validation

By defining validation rules alongside the definition they validate, we can validate any root definition (data, model, usecase, ext, spec, etc) by validating each of the structures in them rather than applying structure-specific validation, like we’re loosely doing now.

For example, the validation rule for required fields, as defined above, would be executed against any data:  type definition, or type that is based on the data: definition. So, the data: definition will be validated the same whether it’s an attribute in a usecase or a Field in a model.

### Validation Modules

Because YAML is just a markup language, we can’t actually execute the yaml to validate itself in the AaC DSL, but, we can tie YAML-based instructions to a python module capable of actually performing validation.

Validation modules will need to implement two new plugin hooks:

```python
@aac.hookimpl
def get_validation_instruction_text() -> str:
    """Returns the validation instruction text associated with this validation module"""
    return "Every validation definition must have a corresponding validator module"

@aac.hookimpl
def validate(model: dict, extended_aac_spec: dict, validator_arguments: list) -> list[str]:
    """Validates the model and returns any errors that might exist."""
    # validate the model
```

**The first hook** `get_validation_instruction_text` returns the validation instruction associated with the module. If we think back to our required validator rule, then that validator module would return “Every field in the required attribute must be defined“. This will be used to map the human instructions in the AaC DSL to each of the validators.

**The second hook** `validate` will validate a single parsed_model with the understanding of the extended language specifications. `model` is the model to validate,` extended_aac_spec` is the Core Spec will all valid installed plugins and extensions applied, and `validator_arguments` are any values specified in the validation.arguments that are defined.

Each model that’s validated will be evaluated for applicable validation rules sourced from the model’s composition and inheritance of other definitions. For instance, if the model being validated is an extension, defined with the root `ext`, then the model would be ‘decomposed’ into its super-structure's `ext` and then `data`. By identifying that an extension needs to be validated by any rules defined for `ext` and `data` then our `model` in this example will be validated by the following validation rules:
1. One and only one field must be defined <enumExt, dataExt>
2. Every field in the required attribute must be defined
3. Every text instruction must have a corresponding validator module

### New Validation Flow

Validator 2.0 will use a similar flow to the current validation method, and validating our example extension model would look like:

1. Load in the Core AaC Spec
2. Load in all currently installed plugin specifications and extend the Core Spec
  a. For each plugin validate the plugin’s extensions + definitions
  b. If valid, apply the extension to the Core Spec models
3. Load the model to validate
4. Validate the models' structure
  a. The model only has the fields defined by its type
5. Identify the model’s deep structure
  a. Extension definition → ext → data
6. Gather applicable validators
  a. One and only one field must be defined <enumExt, dataExt>
  b. Every field in the required attribute must be defined
  c. Every text instruction must have a corresponding validator module
7. Validate the Extension definition against the collected validators
8. Report any errors on the model

### Considerations
1. Should we provide validator modules the unextended AaC Spec? The only time we use this is when we’re validating plugins before extending the core spec.
