### DISCUSSION TITLE
Help with #113

### DISCUSSION THREAD

**Discussion by BryanBailey11** [DevOps-MBSE/AaC#126] [Archive] [answered]
Now that I have dug into this task a little deeper (and I will make sure to clear these things up at the beginning of the sprint next time). I am unsure of the second AC in issue #113 "Must change requirement reference to become a list of strings." in the Aac_Spec.py file all "requirement references" look to already be set up as lists.

**Comment by Coffee2Bits** [comment, marked as answer]
Looking at the story and the AaC Spec, it looks like you're correct that the following would meet the AC:

```yaml
data:
  name: RequirementReference
  fields:
    - name: ids
      type: string[]
  required:
    - ids
```

The AC defines what we'd expect the end result to look like, not necessarily the tasks necessary to complete the story. So, it looks like the second AC is an easy win.
