### DISCUSSION TITLE
Workspaces - AaC Projects

### DISCUSSION THREAD

**Discussion by Coffee2Bits** [DevOps-MBSE/AaC#191] [Archive] [answered]
This proposal describes a new AaC feature: Workspaces. Workspaces are equivalent to a project; a file with the extension `.aac` constitutes a Workspace declaration. A workspace file `example.aac` would contain yaml-based configuration that includes:
* AaC project metadata
  * Name
  * Version
  * License
  * Copyright
* Source file location(s)
  * Define recursive directory targets
  * Define single-files
  * Define non-recursive directory targets (I it worth adding directories that aren't recursively parsed?) 
* Dependency declarations
  * Declare an AaC dependency via URI 
* AaC plugin profiles
  * Declare active vs installed plugins
  * Declare project-level plugin dependencies
  * Declare which plugins need to be installed _and_ active

These workspace files can provide all of the project-level configuration necessary for an AaC project to be built from scratch in a new environment, including plugin and AaC dependencies--perfect for improving the experience of shared collaboration on AaC projects.

The idea is that a Workspace is another name for an AaC project, but since the project's configuration includes configuration that impacts the UI/IDE the scope is more akin to a workspace, hence the preference for "Workspace" over "Project".

## Main Value Props
* Configuration of AaC projects can be maintained as code
* Manages project-level dependencies
* Allows for project-level plugin management
* Allows for complex source file management
* Can be leveraged for parallel model designs 
  * Ideal for concurrent iterations
  * Great for a parallel project updates such as plugin migration
* Provides a clear "entrypoint" to the system
  * Usecase definitions in source directories will be loaded into the context just like their referenced models
  * No need for a root model, can support multiple modelled systems
* A single-sourced project-level designation provides a clear boundary to the modeled system(s) and component(s) 
  * Critical step for implementing interactions between modeled systems and environments 

## Workspace Context
By declaring source directories, AaC dependencies, and plugin dependencies each workspace can drastically vary from another workspace in terms of what definitions are loaded and what constitutes a valid model. I propose that the "context", or global list of loaded AaC definitions like the current validator `validation_context`, is correlated 1:1 to a workspace. This will prevent dependency and plugin clashes by enforcing them at the same level as the requirements are defined.

## Importing Files
If we're managing which AaC files are contributing to a workspace's definitions context via the workspace file, do we really need to maintain file imports? 

Yes, and we should expand on it. If we were to remove file imports then **we would force users into a solely workspace oriented path.** If we implement workspaces we should be cognizant of how that creates a secondary workflow to the one that we've already implemented, where a user can leverage the full AaC feature set _without_ a workspace.

If workspaces end up supporting complex URI resolution for sources like the web URLs, git repositories, local files, etc, then we'll want to consider extending that same flexibility to the import functionality. 

## Issues Addressed
This workspaces proposal would address a number of outstanding questions such as:
* Breaking up AaC projects over multiple files 
* Managing 3rd party AaC definitions
  * https://github.com/jondavid-black/AaC/issues/119
  * https://github.com/jondavid-black/AaC/issues/63
* Which file constitutes the "main" entry point to the modeled context
* Managing AaC dependencies
* Managing plugin "profiles" or active vs inactive plugins
* Managing plugin dependencies for projects

**Comment by jondavid-black** [comment, marked as answer]
I really like this idea.  I would suggest we use `.aac_config` to define the workspace.  I believe we'll find it valuable to use `.aac` file extensions for AaC model files in the future.  This allows users to clearly identify AaC files by file name and will give us a file extension to associate with when we build VS Code editors.

**Reply by Coffee2Bits** [reply]
Sounds good. I agree that there's a lot of value in leveraging `.aac` with the VSCode extension. 

We can follow the vscode style convention for their workspace file name and have ours be 
`<workspace-name>.aac-workspace.`

**Comment by Coffee2Bits** [comment]
Captured this discussion starting with this issue #267.

**Comment by lizzcondrey** [comment]
While this has been marked as resolved, the work associated has still not been completed based on the linked issue. So, leaving open for evaluation of status.

**Reply by jondavid-black** [reply]
I've taken a slightly different approach on this as I experiment with the Pure-Ole-Python (POP) API.  I've created a minimalist way to declare a project and added a ```gen-project``` command.  I have done initial testing and it seems to work.  I've intentionally omitted the concept of active vs inactive plugins.  I'm of the opinion we need to embrace 3rd party plugins much more than we have in the past. 
 To enable or disable a plugin, I'd just like to use ```pip install aac-plugin-name``` going forward, but I'd appreciate feedback on that.  Here's what a project definition looks like in the experimental branch.

```yaml
schema:
  name: Project
  package: aac.lang
  root: project
  description: |
    A definition for an AaC project. Projects provide an environment to define
    plugins your team can use to  extend AaC to meet your unique needs.
  fields:
    - name: name
      type: string
      description: |
        The name of your project.
    - name: description
      type: string
      description: |
        A brief descritpion of your project.  This will initialize your project read me file.
    - name: uses
      type: ProjectDependency[]
      description: |
        A list of pypi dependencies to include in the project.  This can be particularly
        useful if you're leveraging other AaC plugins in your project.  You will get the AaC
        core project by default, so no need to include it here.
---
schema:
  name: ProjectDependency
  package: aac.lang
  description: |
    A pypi project dependency.
  fields:
    - name: name
      type: string
      description: |
        The name of the pypi project to import.
      is_required: true
    - name: version
      type: string
      description: |
        The version nof the pypi project to import.
      is_required: true
```
