### DISCUSSION TITLE
Should we generalize required fields to a validator plugin?

### DISCUSSION THREAD

**Discussion by cvchaparro** [DevOps-MBSE/AaC#281] [Archive]
With all the work Alex has done on Validator 2.0, it occurred to me that the validator plugins (in my opinion) would be a natural home for required fields. I think the way we currently have it made sense in our original version of the validator because we needed some way to distinguish between optional and required fields; but I think "all required fields are present" is a clear candidate for a built-in validator plugin.

I'm still wrapping my mind around Validator 2.0 so I may have some syntax wrong, but I think the idea would be to replace something like this:

```yaml
data:
  name: usecase
  fields:
    - name: name
      type: string
      description: |
        The name of the use case.
    - name: description
      type: string
      description: |
        An explanatory description of the use case to include what purpose the
        use case serves, design ideas when fulfilling the use case, etc.
    - name: participants
      type: Field[]
      description: |
        A list of participants in the use case.

        Generally, these would be users, other systems, etc. that are
        interacting with the system during the course of the use case.
    - name: steps
      type: Step[]
      description: |
        A list of steps taken in the use case.

        See 'Step'
  required:
    - name
    - participants
    - steps
```

with something like this:

```yaml
data:
  name: usecase
  fields:
    - name: name
      type: string
      description: |
        The name of the use case.
    - name: description
      type: string
      description: |
        An explanatory description of the use case to include what purpose the
        use case serves, design ideas when fulfilling the use case, etc.
    - name: participants
      type: Field[]
      description: |
        A list of participants in the use case.

        Generally, these would be users, other systems, etc. that are
        interacting with the system during the course of the use case.
    - name: steps
      type: Step[]
      description: |
        A list of steps taken in the use case.

        See 'Step'
  validation:
    - name: All required fields are present
      arguments:
        - name
        - participants
        - steps
```

Unless I have it completely wrong, you can see that the syntax is nearly identical and it keeps all validation rules (of which "required properties" is one) together under the `validation` key.

Some considerations:
1. If we convert our current `required` keyword to a validator plugin, I think virtually everything will work the same way from a user's perspective except for the way in which we specify the required fields - i.e. by default, all fields are optional; a user specifies required fields in a list (the main difference being where the list is consumed).
2. The validator plugin approach makes the core AaC language a bit smaller.
3. Validating that required fields are present is logically where it belongs (IMO) - with the other validators.
