### DISCUSSION TITLE
Reporting Plug-In

### DISCUSSION THREAD

**Discussion by jondavid-black** [DevOps-MBSE/AaC#317] [Ideas]
We need a way to allow users to "ask questions" of the models they create.  The idea here is to create a reporting plugin that will traverse a model and produce a "flat" set of results from the structured model.  These results could then be output as YAML or CSV in a generic way or provided into the templating engine for more tailored results.

Challenges will be establishing a means for report definitions to be created so that users can traverse lists, nested data, references, etc.  A particularly challenging (but valid) scenario would be circular references that make sense in terms of a data model but create infinite nesting when populated with data.  An example of this can be found in the material-model plugin where assemblies reference sub-assemblies of the same type.  If a sub-assembly happens to reference an assembly in the "parent assembly" definition it will recurse forever.  In this instance this would be an error in the structure of the data model.  We would want the report to fail (perhaps in a pipeline).

If the reporting plugin is sufficiently general purpose it could then be extended to support quality checks on the model.  As an example, let's consider the material-model plugin again.  Imagine a budget is set for a particular deployment.  As the design team develops the parts and assemblies that go into that deployment, it would be valuable to run a report and evaluate the total price of the deployment against the latest changes to the model.  Perhaps thresholds could be set to warn the team as they cross the 90% budget and produce an error when they cross the 100% budget.  The same approach could be applied to evaluate architectural quality attributes such as number of inputs or outputs.  For example, a model with no inputs or outputs may not do anything...and therefore a warning may be generated to inform the team of a potential problem.

So how would this potentially work?  An initial thought is to define a data model for a ```report``` that includes information on the fields in the report (assuming we would want to keep the report output flat) and the details of how to populate each field from an AaC yaml definition.  This report would have to support traversing references and performing manipulation of data (i.e. add, multiple, append, etc.).  I think it would be an interesting exercise to brainstorm and suggest various solutions for report definitions in this discussion.

**Comment by jondavid-black** [comment]
I've started a branch named ```reporting``` to begin experimenting with this idea.

At the core is the definition of a report.
```yaml
data:
  name: Report
  description: A report definition for interrogating AaC models.
  fields:
    - name: title
      type: string
      description: The title of the report.
    - name: description
      type: string
      description: A description of the report.
    - name: get
      type: DataField[]
      description: Report fields taken directly from data model fields.
    - name: calculate
      type: CalculatedField[]
      description: Report fields generated using a formula and content from fields defined under 'get'.
    - name: cross-refs
      type: CrossRef[]
      description: Defines relationships between AaC data types to be traversed by the report generator.
  required:
    - title
    - get
```
The data to be interrogated will be imported in the report definition using the standard approach.  This may not be ideal in all circumstances, but it seems somewhat reasonable as an easy first step.  An alternative would be to specify the AaC model to be interrogated as an argument to the ```report``` command.

Data types taken from the DataField entries would come from the parser as a dict and be flattened so that the field name can use "dot notation" for easy identification within nested data structures.  The initial tests should just use a single type to demonstrate data extraction into a report.

CalculatedField adds complexity in the definition of the formula to be used in calculating the reported value.  The initial concept is to define a set of operations that can be performed on data already present in the DataField entries.  Initially to simplify the complexity we may want to allow only a single operation per CalculatedField.  Note that these intermediates could be marked as hidden to suppress inclusion in the report output.

The next complexity to address is traversing cross references in the data model.  For now, I've just defined a type to capture these cross-references.  It is important to recognize that this should only be applicable for true cross-references, and not necessary for nested data definitions.  It is these cross-references where substantial fan-out in the quantity of reported data can occur.  There is also the potential for circular references which must be detected and raised as errors.  Note that circular references in the data definition should be acceptable, but data content may not be self-referential as it would lead to infinite data traversal.

Once reporting is in place, we may consider adding some evaluations to the report.  These would be tests that evaluate the contents of the reported fields.  Perhaps the approach we establish for handling formulas in CalculatedField could be used here as well, except the resulting value must be boolean.  This could be used by teams to define quality checks, establish budgets, and test these in a pipeline.  Reporting levels such as Info, Warning, and Error could be useful for objective evidence generation and pipeline execution control.
