### DISCUSSION TITLE
Schema Inheritance?

### DISCUSSION THREAD

**Discussion by Coffee2Bits** [DevOps-MBSE/AaC#383] [Ideas]
One of the discussions I'm having with an early adopter is the ability to define inheritance for OOP data structures. We don't currently have a mechanism to support defining inheritance in `schema` definitions, but the early adopter posed an interesting solution which would be create an additional field in `schema` called `inherits`. The proposed change to the `schema` definition would look like:
```yaml
schema:
  name: schema
  fields:
    - name: name
      type: string
      description: |
        The name of the schema definition.
    - name: inherits
      type: Field[]
      description: |
        Used to define a parent or superclass schema in order to define data structure inheritance.
    - name: fields
      type: Field[]
      description: |
        A list of fields that make up the definition.
    - name: validation
      type: ValidationReference[]
      description: |
        References and additional arguments for validations to apply to the definition.
  validation:
    - name: Root key is defined
    - name: Required fields are present
      arguments:
        - name
        - fields
```

and in practice:

```yaml
schema:
  name: SchemaA
  fields:
   - name: field1
     type: string
---
schema:
  name: SchemaB
  inherits:
   - name: super
     type: SchemaA
  fields:
   - name: field2
     type: integer
```

(The use of field here has a lot of unnecessary info and it can be swapped out for a more streamlined option, such as JD's primitive ref)

# Value
This change allows AaC users to define AaC representations of data structures akin to how those data structures are defined, or will be, regardless of whether those target data structures are using composition or inheritance.

Allowing users to define inheritance of `schema` definitions will support more in-depth document, diagram, and code generation options.

# Impacts
If we're going to allow users to define inheritance for `schema` definitions, then I'd expect the inheritance to work as such: if `schema B` inherits `schema A` then `schema B` has all of the fields defined in `schema A` and the additional fields defined in `schema B`. This will require that we alter how `schema` definitions are treated in order to support `schema` inheritance. (only `schema` definitions will support inheritance, and they can only inherit other `schema` definitions).

This also adds an ephemeral aspect to AaC where the structure is being altered beyond what the user sees in the code, however, we are already experiencing with that with extensions. This impact could be overcome through the LSP tooling and the visualization tooling.
