### DISCUSSION TITLE
Implementing Package/grouping structure through definition name conventions

### DISCUSSION THREAD

**Discussion by Coffee2Bits** [DevOps-MBSE/AaC#468] [Ideas]
I wanted to bring up an idea for implementing a packaging/grouping mechanism for definitions that solely relies on naming conventions as opposed to implementing a separate field or internal mechanism. This topic is becoming more relevant as some of our earlier adopters begin to use AaC with more complex usecases, and we have already had a few questions on the topic.

I propose that we add a package delimiter in the definition name (e.g. using period with `my_company.my_package.my_enum`). We'll just need to document the new naming/grouping convention and provide a few handy API functions for plugin developers who want to leverage that information. 

There is the question of allowing users to specify their own delimiters; I have some reluctance stemming from the mixing of package symbols (e.g. `UML4SysML::Model`, `UML4SysML.Package`). However, if we define the list of package delimiter symbols in the core spec then we can allow users to extend the delimiters in AaC and the `aac.lang.definition.package` API can leverage the delimiter definition's values to handle mixed delimiters (e.g. different plugins using different delimiters). 

This system would be fairly easy to implement with minimal impact, and I don't see the need for implementing complex features like package visibility.

Examples would look like:
```
schema:
  name: SystemA.Data
  fields:
    - name: metadata
      type: MessageMetadataData
    - name: transformed_msg
      type: string
---
schema:
  name: SystemB.Data
  fields:
    - name: metadata
      type: MessageMetadataData
    - name: code
      type: fixed64[]
```

What are your opinions?

**Comment by jondavid-black** [comment]
What are the end users trying to accomplish by using such a packaging scheme?  As an old java developer, I tend to think of packaging in pretty specific ways that may or may not apply to modeling.  Is this really about name deconfliction?

**Reply by Coffee2Bits** [reply]
Yeah, there is need for name deconfliction. Take SysML for example, it has a `Model` construct just like the core AaC spec so an easy resolution would be to name the structures in the SysML plugin/DSL with a prefix to accomplish something like `Sysml.Model`.

**Comment by jondavid-black** [comment]
It may be beyond the original intent of this discussion, but it seems if we're talking about packaging we should also talk about package distribution and reuse.  If I were to model some reusable widget and want to share it with users, what would that sharing / utilization strategy look like and how would name deconfliction be clearly managed without getting annoying?  This is essentially an argument that everything is always a fully qualified name.  Would users find that practical?

As for package distribution and reuse, here are some thoughts that would augment our existing pure file-based approach:
- Git repo:  Provide some way to specify a git repo path to reference imported files.
- Zip:  Provide some way to specify a zip file and content path to reference imported files.
- Artifact repo + zip:  Extend the zip solution to include a path for an artifact repo to obtain the zip.
- URL:  Just a simple URL to a file location rather than a file system path.
- URL + zip:  Extend the zip solution to include an arbitrary URL path to obtain the zip.

If we had inheritance (#652 ) could we make the import list contain a "import target" schema which serves as a parent type for various specific endpoints?  It may look something like this:

```yaml
import:
  - file: ./my_model.yaml
  - url:  http://www.myfiles.org/my_system/my_model.yaml
  - zip: ./my_system.zip /my_system/my_model.yaml
  - url-zip: http://www.myfiles.org/my_system.zip /my_system/my_model.yaml
  - git:  http://www.github.com/user/repo/models/my_system/my_model.yaml
  - repo:  http://www.my_nexus.org/repo_name/models/my_system/my_model.yaml
  - repo-zip:  http://www.my_nexus.org/repo_name/my_system.zip /my_model.yaml
```
