### DISCUSSION TITLE
Add Command args to plugin commands

### DISCUSSION THREAD

**Discussion by Coffee2Bits** [DevOps-MBSE/AaC#53] [Archive] [answered]
### Problem Description ⚠️
As a user and a plugin developer, I am limited by the minimal command configuration available: 
- I'm limited in the information my plugin can be provided, I can only access `arch_file` and`parsed_models`
- I'm limited in the lack of independent arguments for plugin commands, all my plugin commands have to use the same two arguments
- I'm limited in the help information that's reported to the user via the '-h' command, there is no help information concerning the inputs for my plugin commands

Currently, when a plugin is registered via name and description, and that's it. There is no method for a plugin author to specify different arguments for their plugin commands, or even just add additional help information about the plugin command arguments.

### Proposed Solution 💡
I'd like to propose adding variable command inputs and improved help command feedback for plugin commands. 

The outcome will allow plugin commands to:
- Define command input parameters independently of other commands
- Define helpful contextual information for their plugin command arguments

####  1. Extend the command AaC definition to include input descriptions
By adding additional context like a description for behavior input definitions as show below, we can pass this extra contextual information to the user. 

Add to the yaml definition
```yaml
behavior:
    - name: gen-plugin
      type: command
      description: Returns the gen-plugin command type to the plugin infrastructure.
      input:
        - name: arch_file
          type: str
          description: The path to the plugin's AaC yaml file # New Line
      acceptance:
        - scenario: Output PlantUML component diagram for valid architecture.
          given:
            - The {{puml.input.parsed_model}} contains the parsed content from architecture_file.
          when:
            - The aac app is run with the puml-component command.
          then:
            - A PlantUML component diagram of the model is printed to the console.
```

Extend the AaCCommand structure
```python
class AacCommand:
    """
    A class used as a struct to hold a command name, command description, and callback.
    The command name is added to the argument parser with help set to teh command description.
    The callback is invoked if the user specifies the command.
    """

    def __init__(self, command_name: str, command_description: str, callback: Callable, arguments: list[AacCommandArgument]) -> None:
        self.command_name = command_name
        self.command_description = command_description
        self.callback = callback
        self.arguments = arguments # New list of 

class AacCommandArgument:
    """
    A class used as a struct to hold a command argument name and description.
    """

    def __init__(self, name: str, description: str) -> None:
        self.name = name
        self.description = description
```

Example Console output:
```bash
$ aac gen-plugin -h
usage: aac gen-plugin [-h] --arch-file ARCH_FILE

optional arguments:
  -h, --help            show this help message and exit
  --arch-file ARCH_FILE
                        path to a plugin AaC yaml file.
```

####  2. Register AaC Command Arguments
The current plugin registration would need to be altered slightly to parse through the behavior's input to generate command arguments. 

Current Implementation:
https://github.com/jondavid-black/AaC/blob/ff5f7b23d76d31a72a51fc6ea4c0160be9c59681/src/aac/cli.py#L79-L81

Proposed Implementation:
```python
    for cmd in aac_plugin_commands:
        cmd_parser = command_parser.add_parser(cmd.command_name, help=cmd.command_description)

        for arg in cmd.arguments:
            cmd_parser.add_argument(
                name_or_flags=arg.name, help=f"{arg.description}" 
                # Other options could be used, like `required=arg.required`
            )

    return arg_parser, aac_plugin_commands
```

####  3. Map parser args to the plugin's arguments.
Since we have variable function arguments, we'll need to use keyword arguments when executing the command callback. 

A keyword argument map will need to be created for the function, which can be done by expanding the `AacCommand` class or by leveraging the `inspect` module as demonstrated below:
```python
inspect.signature(cmd.callback) # evaluates to "(arch_file: str, parsed_model: dict)"
```

Once arguments are prepared in a dict of keyword argument names to argument values, we can execute all plugin commands in a generic fashion like:
```python
    for cmd in aac_plugin_commands:
        if args.command == cmd.command_name:

            keyword_args = {}
            parameters = inspect.signature(cmd.callback).parameters.keys()
            for parameter in parameters:
                keyword_args[parameter] = args[parameter]

            cmd.callback(**keyword_args) # **kwargs
```

### Other Changes
If the proposed change is accepted, it opens the door for some other functionality such as optional command arguments.
