### DISCUSSION TITLE
Moving imports out of definitions and into a file-wide definition/header?

### DISCUSSION THREAD

**Discussion by Coffee2Bits** [DevOps-MBSE/AaC#569] [Ideas]
We currently have imports as a second top-level key in our yaml definitions in order to declare a file dependency for a definition or even multiple definitions. However, this can lead situations where definitions aren't declaring the imports they need, but the issue isn't visible since we only need the file to marked for import once. This also gets convoluted because you can have definitions that don't need a file import yet import a file that's actually needed by other definitions. The per-definition importing isn't strict enough to provide clear definition dependencies, so I'm arguing that we treat it as a file-wide dependency declaration.

So, instead of the file `AaC/python/model/material/living_room.yaml` looking like this:
```yaml
import:
  - ./amazon_parts.yaml
  - ./furniture_store.yaml

assembly:
  name: Seating_Area
  description:  The place I'll hang out a lot.
  parts:
    - part-ref: Couch
      quantity: 1
    - part-ref: Arm_Chair
      quantity: 1
    - part-ref: Coffee_Table
      quantity: 1
    - part-ref: Side_Table
      quantity: 2
    - part-ref: Table_Lamp
      quantity: 2
    - part-ref: Coasters
      quantity: 1
---
import:
  - ./amazon_parts.yaml

assembly:
  name: Entertainment_System
  description:  Mostly electronic toys
  parts:
    - part-ref: TV
      quantity: 1
    - part-ref: Sound_Bar
      quantity: 1
    - part-ref: X_Box
      quantity: 1
    - part-ref: Wifi_Router
      quantity: 1
```

It would look like this:
```yaml
import:
  - ./amazon_parts.yaml
  - ./furniture_store.yaml
---
assembly:
  name: Seating_Area
  description:  The place I'll hang out a lot.
  parts:
    - part-ref: Couch
      quantity: 1
    - part-ref: Arm_Chair
      quantity: 1
    - part-ref: Coffee_Table
      quantity: 1
    - part-ref: Side_Table
      quantity: 2
    - part-ref: Table_Lamp
      quantity: 2
    - part-ref: Coasters
      quantity: 1
---
assembly:
  name: Entertainment_System
  description:  Mostly electronic toys
  parts:
    - part-ref: TV
      quantity: 1
    - part-ref: Sound_Bar
      quantity: 1
    - part-ref: X_Box
      quantity: 1
    - part-ref: Wifi_Router
      quantity: 1
```

This move would help in reducing redundant references to file names, and the non-standard behavior of `import` being that it is the only root key that can share a yaml document with another root key (e.g. `model` and `enum` in the same yaml document would be invalid.)

Thoughts?
