### DISCUSSION TITLE
Implement Inheritance in AaC

### DISCUSSION THREAD

**Discussion by jondavid-black** [DevOps-MBSE/AaC#652] [Ideas]
This discussion will explore the incorporation of inheritance into AaC.

**Comment by jondavid-black** [comment]
# AaC Inheritance

We've intentionally avoided modeling inheritance in AaC in the past under the thought process that each decomposed element of a system should be a unique entity.  As we consider creating tangible models of real-world systems, we're discovering that an ability to model using inheritance would be valuable.  This directory attempts to provide an example of using inheritance in a generic model.

Inheritance can have a number of different characteristics to consider.  I propose we keep inheritance modeling relatively simple but must account for some nuiances.  We will need some way to indicate that a model or schema parent is or isn't something that can be realized.  If there are no modifiers, the model or schema can be realized.  If an "abstract" modifier is applied the parent cannot be realized.  This provides a means of establishing interface definitions.  We will allow for multi-parent inheritance.

## Reuse Ext to support inheritance
After writing this narrative I realized we already have the ext capability which may cause confusion.  We may want to consider repurposing ext to be used for inheritance rather than modification.  If we did this, the difference would be using ext to create a new type that inherits from the referenced type rather than modify the referenced type.  In this instance, we'd have to enable the new type to be polymorphic in its use...which may be clearer to anyone who is an OOA/OOD experienced individual. I've created the examples to use the ext tag to define inheritance 

The ext field currently only supports extending schema and enum.  I think we'd have to enable extending models as well.  I think some use case thought is needed to ensure we create something that adheres to our objective of clarity while still providing useful inheritance functionallity.  For example, would it make sense to ext a model to add new components or behaviors?

# Sample Model

We'll have a "test system" that contains an echo and color service.  The echo service simply listens for a message and responds with the same content as was provided. The echo service is a type of a monitored service that includes behaviors to track the number of invocations and time used by the service in executing the behavior.  The color service receives a named color and provides the RGB values for the color.  Color service is also a monitored service. We should assume that there could be a variety of explicit serivices that would also be of type monitored service.  The intent here is to show the use of inheritance in model definition.

We will also show inheritance in schema definition.  In this instance we'll define a message that contains a header field to capture metadata.  We'll then define concrete messages that extends the message schema with some unique content.  In this case the unique content will be a color.  We can image a case where a model defines a behavior with the color message as an input.  Because color message has message as a parent in the inheritance structure, it will inherit the header field from its parent type.

```yaml
model:
  name: TestSystem
  description: Simple Service that does stuff.
  components:
    - EchoService
    - ColorService
```

```yaml
model:
  name: MonitoredService
  modifier: abstract
  description: Base service definition that collects runtime information.
  behavior:
    - name: getMetrics
      type: REQUEST_RESPONSE
      description:  Retrieve service runtime information.
      output:
        - name: call_count
          type: int
          description: Total number of service behavior invocations not counting base MonitoredService behaviors.
        - name: call_runtime
          type: int
          description:  Total number of milliseconds the service has processed invocations.
      acceptance:
        - scenario: Normal operations
          given:
            - The service is running.
            - The reset is invoked.
            - One non-base service behavior is invoked.
          when:
            - The getMetrics is invoked.
          then:
            - The call_count output is 1.
            - The call_runtime output is greater than 1.
    - name: reset
      type: REQUEST_RESPONSE
      description: Resets utilization data.
      acceptance:
        - scenario: Service Resets Metrics
          description: The reset is called to ensure metrics are clean.
          given: 
            - The service is running.
          when: 
            - The reset is invoked
          then:
            - The reset returns true indicating successful metric reset.
            - The getMetrics returns 0 for call_count.
            - The getMetrics retusns 0 for call_runtime.
```

```yaml
ext:
  name: EchoService
  parent: 
    - MonitoredService
  description: Echoes a reqeust back as a response.
  modelExt:
    behavior:
      - name: echo
        type: REQUEST_RESPONSE
        description:  Replies to an input with the same data in the output.
        input:
          - name: request
            type: string
            description: Some random string to echo back.
        output:
          - name: response
            type: string
            description: The same data provided in the request.
        acceptance:
          - scenario: Normal operations
            given:
              - The service is running.
            when:
              - The echo is invoked with request "Hello World!".
            then:
              - The echo returns response of "Hello World!".
```

```yaml
ext:
  name: ColorService
  parent: 
    - MonitoredService
  description: Provides RGB values for a named color.
  modelExt:
    behavior:
      - name: getRGB
        type: REQUEST_RESPONSE
        description:  Replies to an input with the numerical RGB values for a named color.
        input:
          - name: request
            type: ColorMessage
            description: Some named color to evaluate.
        output:
          - name: response
            type: ColorRGB
            description: The rgb values for the named color.
        acceptance:
          - scenario: Normal operations
            given:
              - The service is running.
            when:
              - The getRGB is invoked with named color "purple".
            then:
              - The getRGB returns response of Red = 128, Green = 0, and Blue = 128.
```

```yaml
schema:
  name: Message
  modifier: 
    - abstract
  description: A generic based message that provides a common header for all messages.
  fields:
    - name: header
      type: Header
      description: Message metadata
```

```yaml
schema:
  name: Header
  description: Metadata for a message.
  fields:
    - name: Time_Created
      type: time
      description:  The time the message was created.
    - name: Creator
      type: string
      description: The name of the entity who created the message.
```

```yaml
ext:
  name: ColorMessage
  parent: 
    - Message
  description: Message with a color
  schemaExt:
    - name: color
      type: string
      description: Common color name (i.e. red, bule, green, purple, etc.)
```

```yaml
ext:
  name: ColorRGB
  parent: 
    - Message
  description: Message with a color RGB
  schemaExt:
    - name: red
      type: int
      description: Red numerical value for a color.
    - name: green
      type: int
      description: Green numerical value for a color.
    - name: blue
      type: int
      description: Blue numerical value for a color.
```

# Inheritance Validation

An initial set of thoughts on validating a model that uses inheritance:

1. When we define a model or schema, we will allow any field to be populated with an object of the defined type or a sub-type.  Anything else will be a validation failure.
1. When we define a parent type, it must exist within the imported "model definition space".
1. If a child schema contains a field with the same name as the parent, validation fails.  
1. If a child model contains a behavior with the same name as the parent, validation passes and the behavior is assumed to be overridden.
1. If a child model contains a behavior with the same name but different attributes (i.e. input or output), validation fails due to the override being broken.
1. If a circular inheritance chain is discovered, the validation fails.

# Generation Behaviors

An initial set of thoughts on generating content from a model that uses inheritance:

1. Protobuf example:  A child object will inherit all fields from the parent.  Fields defined in the child are appended to fields defined in the parent.  The generated protobuf will include the complete set of fields from parent and child.
1. Code generation:  Any parent / child model will result in a class for both the parent and child with an inheritance relationship between them.  Behavior in the parent will be stubbed into the parent class.  If the parent is modified to be abstract, the parent class will be abstract.  Behavior in the child will be stubbed into the child class. 
1. Figure genreation:  Need to update PUML plugin to properly recognize and handle inheritance.

# Notes

There are some potentially confusing core content that we should evaluate as we implement inheritance.

- Schema currently contains a field called inherits.  What is this and how is it used?  Should it be removed?
- Ext currently has a field called type which should probably be renamed to parent.
- Would it be cleaner to simply eliminate the ext type and provide an optional parent field in schema, model, and enum?  Would this even work?
- Generally speaking, we've tried to keep linkages top-down (i.e. model -> components).  This was driven by an initial preference to employ composition over inheritance.  Inheritance necessarily drives bottom-up linkage for parent references.  We just need to look things over and make sure there are no surprises to overcome based on initial assumptions.

**Comment by jondavid-black** [comment]
After a little more thought, I think the right answer here is to eliminate the ext type and just use a parent field to indicate inheritance.  The constraint would be that models, schemas, and enums can only have inheritance within themselves.  Only models can inherit from models and only schemas can inherit from schemas.  A model cannot inherit from a schema.

**Comment by jondavid-black** [comment]
I've been thinking about how our decisions on inheritance may impact existing plugins.  The protobuf plugin is a good topic of debate as it extends the primitive enum.  Should this change with inheritance and if so how should it change?

Option 1:  Keep ext as it is
- Perhaps just constrain this to the enum?

Option 2:  Remove ext
- The plugin developer would have to create a subtype of Primitives
- The plugin developer would have to create a subtype of Field that uses the new Primitives subtype containing a different 'type', perhaps called 'pbtype'
- Any schema used to generate protobuf would have to use the protobuf field rather than the base field.  How would this be validated?

The protobuf plugin also extends some schema types.  This raises the question of how the validator may work if we were to use inheritance instead of ext.  Here's an initial thought that may or may not work.

1.  Begin validation using the supertype.  If that passes, proceed.
2. If supertype validation fails, attempt to validate against subtypes.  If a subtype exists that passes validation, proceed.
3. If subtype validation fails, attempt to validate sub-subtypes.  Continue the validation attempt throughout the inheritance structure until one passes or all fail.  If all fail, fail validation.

Unfortunately, this could be a rather involved process...particularly if someone gets "inheritance happy" in their model.  It would require that we have an ability to getSubtypes() from a definition.  I suppose we'll have to do something similar due to the nature of inheritance, so does this provide any additional rationale for or against keeping ext?

I suppose my opinion has changed on the topic since my last post.  I think it is possible to eliminate ext and force everything to use inheritance, but I also think that takes away a powerful tool from a modeling team.  A great advantage of ext is it's simplicity.  Enabling teams to quickly establish domain specific modeling is valuable.  So my current thought is we do both inheritance and ext.  This has the additional advantage of not forcing us to another breaking version change.

**Reply by jondavid-black** [reply]
I need to update the examples provided previously based on this additional thought and see how it works out.  I'll try to get that in place today.

**Comment by jondavid-black** [comment]
Updated inheritance examples:

Model inheritance example is a parent abstract MonitoredService that defines metadata behaviors and child services that perform business logic behaviors.

```yaml
model:
  name: MonitoredService
  modifier: abstract
  description: Base service definition that collects runtime information.
  behavior:
    - name: getMetrics
      type: REQUEST_RESPONSE
      description:  Retrieve service runtime information.
      output:
        - name: call_count
          type: int
          description: Total number of service behavior invocations not counting base MonitoredService behaviors.
        - name: call_runtime
          type: int
          description:  Total number of milliseconds the service has processed invocations.
      acceptance:
        - scenario: Normal operations
          given:
            - The service is running.
            - The reset is invoked.
            - One non-base service behavior is invoked.
          when:
            - The getMetrics is invoked.
          then:
            - The call_count output is 1.
            - The call_runtime output is greater than 1.
    - name: reset
      type: REQUEST_RESPONSE
      description: Resets utilization data.
      acceptance:
        - scenario: Service Resets Metrics
          description: The reset is called to ensure metrics are clean.
          given: 
            - The service is running.
          when: 
            - The reset is invoked
          then:
            - The reset returns true indicating successful metric reset.
            - The getMetrics returns 0 for call_count.
            - The getMetrics retusns 0 for call_runtime.
```

```yaml
model:
  name: EchoService
  parent: 
    - MonitoredService
  description: Echoes a reqeust back as a response.
  behavior:
    - name: echo
      type: REQUEST_RESPONSE
      description:  Replies to an input with the same data in the output.
      input:
        - name: request
          type: string
          description: Some random string to echo back.
      output:
        - name: response
          type: string
          description: The same data provided in the request.
      acceptance:
        - scenario: Normal operations
          given:
            - The service is running.
          when:
            - The echo is invoked with request "Hello World!".
          then:
            - The echo returns response of "Hello World!".
```

```yaml
model:
  name: ColorService
  parent: 
    - MonitoredService
  description: Provides RGB values for a named color.
  behavior:
    - name: getRGB
      type: REQUEST_RESPONSE
      description:  Replies to an input with the numerical RGB values for a named color.
      input:
        - name: request
          type: ColorMessage
          description: Some named color to evaluate.
      output:
        - name: response
          type: ColorRGB
          description: The rgb values for the named color.
      acceptance:
        - scenario: Normal operations
          given:
            - The service is running.
          when:
            - The getRGB is invoked with named color "purple".
          then:
            - The getRGB returns response of Red = 128, Green = 0, and Blue = 128.
```

Schema inheritance shows a base Message that includes header data and two child messages related to using the ColorService above.

```yaml
schema:
  name: Message
  modifier: 
    - abstract
  description: A generic based message that provides a common header for all messages.
  fields:
    - name: header
      type: Header
      description: Message metadata
```

```yaml
schema:
  name: Header
  description: Metadata for a message.
  fields:
    - name: Time_Created
      type: time
      description:  The time the message was created.
    - name: Creator
      type: string
      description: The name of the entity who created the message.
```

```yaml
schema:
  name: ColorMessage
  parent: 
    - Message
  description: Message with a color
  fields:
    - name: color
      type: string
      description: Common color name (i.e. red, bule, green, purple, etc.)
```

```yaml
schema:
  name: ColorRGB
  parent: 
    - Message
  description: Message with a color RGB
  fields:
    - name: red
      type: int
      description: Red numerical value for a color.
    - name: green
      type: int
      description: Green numerical value for a color.
    - name: blue
      type: int
      description: Blue numerical value for a color.
```

**Comment by Coffee2Bits** [comment]
This response is bit lengthy, so I apologize upfront. If we remove extensions then there are a number of impacts we need to deal with, and it dovetails nicely with the discussion of broader inheritance in AaC. There are definitely some areas for refinement in my proposal, but I tried to capture the flexibility and uses that I currently see for these proposed changes.

At first I was hesitant to remove the `ext` key since we use it heavily for defining new root keys and primitives types, however, if we implement a generic inheritance method for AaC then I believe we can keep primitives and the root keys while providing users a much more powerful iteration of the AaC DSL. The thoughts that I have captured are large enough that it would likely take the team an iteration to overhaul the engine and it would necessitate AaC version 3.0.0.

Thinking on this, I also found myself really coming to love the idea of `modifier` as an analogue to [UML/SysML stereotypes](<https://en.wikipedia.org/wiki/Stereotype_(UML)>): `They allow designers to extend the vocabulary of UML in order to create new model elements, derived from existing ones, but that have specific properties that are suitable for a particular domain or otherwise specialized usage.` I'll expand on this further below, but whenever I talk to our senior and principal DevSecOps engineers at Zaden about modeling complex applications and their infrastructure I hear about the desire to document minutia such as sub-nets, IP addresses, and resource infrastructure and redundancy (think documenting K8s pods strategies). Modifiers being in the same vein as stereotypes could lend themselves greatly to documenting those low-level details in AaC models and bridging the last mile to make it effective for highly-detailed architecture capture and useful for things like documenting infrastructure for compliance -- something we've encountered in meeting compliance with standards such as [CMMC](https://dodcio.defense.gov/CMMC/).

Lastly, if we proceed with a completely generic inheritance mechanism for AaC definitions, then I think we'll need to include typed `reference` primitives. Assuming that I haven't missed something, then I believe we should only have to deal with inheritance within the typed references and the `extends`, `inherits`, or `parents` field (whichever verbiage we settle on).

## Extends Keyword
Currently, we only support inheritance for `schema` definitions using the keyword `inherits` to designate a parent definition. Given that we're thinking about replacing extensions completely with inheritance, then I propose we change the `inherits` keyword to `extends` and make it available to all definitions. The `extends` keyword would designate a list of definitions of the same root key as superclasses/parents of the definition. We can impose some constraints on these `extends` entries via validation such as the super definition(s) must have the same root type as the definition defining the `extends` field. 

If we take the same approach with all definitions as we have with the `schema` inheritance, then we can generically flow down all of the fields of the super definition(s) to the sub definition. Applying this to all definition types including `schema`, `enum`, `model`, and user-defined types would completely remove the necessity for extensions as long as we account for sub-classes when performing searches for root keys and primitive types defined in the context.

### Extending Enums
I won't reiterate the discussion on extending `schema` definitions as we already have a working implementation, but I think it's important to discuss applying inheritance to enums as they're the only set of definitions distinct enough from `schema` definitions to warrant a deeper dive. The idea is that when `enumB` extends `enumA`, the new enum values defined in `enumB` are effectively appended to the list of values provided by `enumA`. The second part of the magic is that when a field is defined as type `enumA`, our validation that checks whether or not the value of field typed as `enumA` is valid -- per the values defined by `enumA` -- will include enum values in `enumA` extended definitions (`enumB`) as valid enum values for the field. A good example would be extending `BehaviorTypes`, an enum that we've defined in the Core Spec, and can't be edited by users, but may be incomplete in the list of behaviors that users would want to model. Users would simply extend `BehaviorType` like so:
```yaml
enum:
  name: BehaviorType
  values:
    - PUB_SUB
    - REQUEST_RESPONSE
    - STARTUP
    - TIMER
    - LOGGING
---
enum:
  name: MyNewBehaviorTypes
  extends: BehaviorType
  values:
    - MY_NEW_BEHAVIOR
    - SOME_OTHER_BEHAVIOR
---
model:
  name: MyNewModel
  description: Some user-defined model with new behavior types
  behavior:
    - name: someBehavior
      type: MY_NEW_BEHAVIOR
     ...
```

Even though `MY_NEW_BEHAVIOR` isn't defined in `BehaviorType`, users are still able to create valid models with the new behavior type because `MyNewBehaviorTypes` is a sub-class of `BehaviorType`. With our inheritance model, users could also define their own schema with the type `MyNewBehaviorTypes` as a field type and the list of values they can define are the superset of values in `BehaviorType` and `MyNewBehaviorTypes` because `MyNewBehaviorTypes` inherits all of the values of `BehaviorType`.

### Multiple Super-Definitions
Some programming languages allow users to leverage [multiple inheritance](https://en.wikipedia.org/wiki/Multiple_inheritance). With a few constraints, we could implement this for AaC. Since our approach is to simply flow the attributes of the super-definition down to the sub-definition, multiple super-definitions would act fairly similar to a singular super-definition. I've created an example of multiple inheritance where the inherited fields are denoted in the sub-definition `SubDefinition`:
```yaml
schema:
  name: SuperDefA
  fields:
    - name: FieldA1
    - name: FieldA2
  validations:
    - Validation for Def A
---
schema:
  name: SuperDefB
  fields:
    - name: FieldB1
    - name: FieldB2
    - name: FieldB3
  validations:
    - Validation for Def B
---
schema:
  name: SubDefinition
  extends:
    - SuperDefA
    - SuperDefB
  fields:
    - name: FieldSub1
    ## The following fields are not defined, but are present via inheritance
    * name: FieldA1
    * name: FieldA2
    * name: FieldB1
    * name: FieldB2
    * name: FieldB3
  validations:
    - Validation for SubDefinition
    ## The following definitions are not defined, but are present via inheritance
    * Validation for Def A
    * Validation for Def B
```

## Replacing Root Keys with `Instance` 
Once we remove the extensions functionality, we'll need a new way of allowing users to define new types of root keys. I've recently begun thinking of root keys as instance types (Classes) -- each root key defines a new structure that can be instanced with a unique name and set of values. I propose a second change where we replace the `Root` definition with a new type of definition called `Instance`. Each `Instance` defines a top-level key that can be used by the user in the same way that root keys currently operate without needing to extend an existing definition. `Root` would be replaced by a set of definitions like so:
```yaml
schema:
  name: Instance
  fields:
    - name: name
      type: string
    - name: type
      type: reference<Schema> # Preview example of typed-reference
    - name: description
      type: string
---
instance:
  name: instance
  type: Instance
  description: |
    Defines an instance-able definition based on data structure defined 
      by a `schema` definition referenced in the `type` field.
---
instance:
  name: schema
  type: Schema
  description: |
    A definition that defines the schema/structure of definitions.

    A 'schema' definition can alternatively be thought as a defining the
        data structure of a definition.
---
instance:
  name: enum
  type: Enum
  description: |
    A definition that represents an enumerated type of value.

    An example of when to use an 'enum' is when you want to provide several
        different options for a single value.
---
instance:
  name: model
  type: Model
...
```

If users want to define a new type of instance-able definition such as `service` in a service-oriented architecture then they would simply do the following:
```yaml
schema:
  name: Service
  fields: 
  ...
---
instance:
  name: service
  type: Service
  description: A software component of a large software application.
---
service:
  name: MyService
  fields:
  ...
```

## Replacing the Primitives Definition
Primitive types will also be affected by removing extensions, but we can apply the same strategy as prescribed for the root keys/instances above. By allowing users to define instances of primitive types, we can easily allow them to define new primitive types and even assign validations for each primitive type in its definition, something that we currently don't facilitate. This new approach would look something like:
```yaml
schema:
  name: PrimitiveType
  description: Defines primitive types in the AaC DSL
  fields:
    - name: name
      type: string
    - name: description
      type: string
    - name: validations
      type: reference<Validation>[] # Preview for a list of typed-references
---
instance:
  name: primitive
  type: PrimitiveType
  description: Allows users to define primitive types in AaC
---
primitive:
  name: int
  description: Defines the int primitive type, a numerical whole-number value
  validations:
    - Integer is whole number
---
primitive:
  name: date
  description: Defines the date primitive type, an ISO 8601 compliant time stamp
  validations:
    - Date is ISO 8601 compliant
---
...
```
This same example can be leveraged in the `Gen-Protobuf` plugin that defines the set of [Protobuf3-specific primitive types](https://protobuf.dev/programming-guides/proto3/#scalar) for the generation of Protobuf messages, and would include validation for each of those types.

## Modifiers
As I mentioned in the intro, I think this is a fantastic analogue to the UML/SysML `stereotype` and will give us the flexibility to add ad-hoc minutia to models for highly-specialized case such as modelling network and cloud infrastructure in larger applications as well as to address the stereotype gap in the SysML and AaC conversion. Page 28 of the [SysML Specification](https://sysml.org/.res/docs/specs/OMGSysML-v1.5-17-05-01.pdf) demonstrates that stereotypes can be single, enum-like values or more complex structures.

![Screenshot from 2023-09-06 02-52-08](https://github.com/DevOps-MBSE/AaC/assets/60155541/34f887eb-3431-4a85-81b1-d2a802261829)

With this in mind, I propose that we define modifiers as instances of a `schema`-defined structure following the same pattern as proposed for `instance` and `primitive` above:
```yaml
schema:
  name: Modifier
  fields:
    - name: name
      type: string
    - name: description
      type: string
    - name: fields
      type: Fields[] # Fields is optional for Modifier unlike Schema
---
instance:
  name: modifier
  type: Modifier
---
modifier:
  name: Abstract
  description: |
    Denotes that the definition is abstract and can't be referenced unless 
      in the `extends` field of another definition sharing the same 
      root key/instance type.
---
modifier:
  name: View 
  description: Corresponds to the `View` stereotype in SysML
  fields:
    - name: viewpoint
      type: Viewpoint
    - name: stakeholder
      type: Stakeholder[]
---
model:
  name: MyModel
  modifier:
    - Abstract
    - View:
      viewpoint: SomeViewpoint
      stakeholder:
        - Stakeholder1
        - Stakeholder2
  ...
```

## Typed Reference Primitive
As some of the above examples and paragraphs have alluded to, I think we need to incorporate a way to define a set of acceptable types for the `reference` primitive in order to constrain what kind of references can be used as values in certain fields. Since `references` are specifically checking that the value, a definition's name, corresponds to a definition defined in the context then we can provide some constraints on the type of definition that  is referenced based on its type. If we equate the root key/instance key to a class and each definition to an object or instance of a class, then typed references should be able to specify a set of root key/instance keys that are acceptable values for the field. This would cleanly address an existing set of constraints that we're already trying to fill with some validators such as [`Subcomponents are models`](https://github.com/DevOps-MBSE/AaC/blob/5a7e6d0bf7aea0a8337f089fa980e264df357f00/python/src/aac/plugins/validators/subcomponent_type/subcomponent_type.yaml#L8-L43). Instead of using a validator to check that all subcomponents in a `model` are also of the type `model`, we could simply represent this with a typed reference:
```yaml
schema:
  name: Model
  fields:
    - name: name
      type: string
      ...
    - name: description
      type: string
      ...
    - name: components
      type: reference<Model>[]
      description: |
        A list of models that are components of the system.
    - name: behavior
      ...
    - name: state
      type: Field[]
      ...
    - name: requirements
      type: RequirementReference
      ...
  validation:
    - name: Required fields are present
      arguments:
        - name
```
We can still maintain the simple `reference` primitive, but by giving it a typing mechanism not unlike the typing mechanism in C++ and Java, we can allow users to easily constrain what type of definitions can be referenced in that field. For the typed reference, the list of acceptable root keys will be denoted in a pair of angled brackets `<>`. In practice this would look like `reference<Model>` or in an example with multiple types `reference<Model, Schema>`.

Because we're looking to implement inheritance broadly in AaC, these typed references would have to account for Polymorphism like OOP programming languages. Thus, if a field is typed for `model` then any definition that extends `model` would also be a valid subcomponent in our `model` example. If we re-use our service example:
```yaml
schema:
  name: Service
  extends:
    - Model
  fields:
  ... # Additional service fields could go here -- though, this could be duplicate information provided by modifiers
---
instance:
  name: service
  type: Service
  ...
---
service:
  name: DatabaseService
  modifiers:
    - Abstract
  ...
---
service:
  name: MySQLDatabaseService
  extends:
    - DatabaseService
    ...
---
model:
  name: MyWebApp
  components:
    - MySQLDatabaseService
  ...
```

This is a tad convoluted, but with the inheritance we have `MySQLDatabaseService` that extends `DatabaseService` which is an instance of `Service` that in turn extends `Model`. Phrased in a more programmer-centric way: `MySQLDatabaseService` is an object of the class `Service` that is a sub-definition of `Model`. With this relationship we can determine that `MySQLDatabaseService` is ultimately a derivative of `Model` and thus is valid as a subcomponent entry in our larger system model `MyWebApp` with the extra ability to define a set of new, re-usable instance types `service`.
