### DISCUSSION TITLE
Channels in AaC

### DISCUSSION THREAD

**Discussion by jondavid-black** [DevOps-MBSE/AaC#653] [Ideas]
We need some way to show communication channels for controlled interactions.  The original AaC concept was that the data type would be sufficient differentiation, but that is not the case.  Situations may arise where the same data type is distributed and consumed within different contexts.  The concept of an AaC Channel provides a means of establishing the communicaiton context.

At this time we don't need to be overly detailed in the definition of a channel.  We'll start by simply establishing a channel as a named entity associated with a schema.  There will be a one-to-one relationchip between a channel and a schema data type.  Channels may need to have explicit types such as pub-sub or shared-state.  These channel types shouldn't model implementation (i.e. TCP/IP vs UDP multicast), but should provide an indication of how the channel may be used within the model.  It may also be useful to indicate if the channel is external or internal to the system.  This would help with security analysis as each external channel represents an entry point on the system boundary.

Channels are utilized by model definitions in the behavior input, behavior output, and state definitions.

1. Input Channel:  Establishes a subscription to a data type.  Subscription events are triggered when another entity publishes data to the named channel.
1. Output Channel:  Establishes publication of a data type.  
1. State Channel:  Establishes a shared data store.  May result in data events triggered when another entity adds, modifies, or deletes data in the named channel.

## Potential Channel Validation

1. Each channel name must be unique.
1. The schema associated with the channel must exist.
1. A single behavior cannot have the same channel as input and output.
1. A channel assigned to a behavior's input or output must be a pub-sub channel type.
1. A channel assigned to a state must be a shared-state channel type.

## Potential Content Generation

1. Enable expansion to specify authorized communication implementation to include marshalling, ports, and protocols.
1. Generate security documentation for ports and protocols.
1. Generate networking code for an authorized communication implementation.
1. Generate communication diagrams.  Could be used with other future capability such as cloud modeling to show data ingress / egress or data transfer across clusters / regions.

## AaC Channels Example

We'll define a very small system with 2 models performing work.  The first model periodically wakes up and publishes a random message.  It then updates some shared state counter of the number of published messages.  The second model subscribes for the published message, logging the message content to the terminal.  It then updates some shared state counter of the number of received messages.  This example will show a pub-sub channel and a shared-state channel.

First lets define some schemas that the channels will be used to share within the system.
```yaml
schema:
  name: Message
  description: A generic message.
  fields:
    - name: content
      type: String
      description: Message data.
```

```yaml
schema:
  name: Counters
  description: A counting data set.
  fields:
    - name: num_sent
      type: int
      description: Number of messages sent.
    - name: num_recv
      type: int
      description: Number of messages received.
```

Now let's define the channels for these schemas.

```yaml
channel:
  name: Messages
  type: Message
  channel_type: PUB_SUB
  description: Publish & subscribe channel for Message.
```

```yaml
channel:
  name: Message_Counts
  type: Counters
  channel_type: DATA_SHARE
  description: Shared state for counting messages sent and received.
```

And finally we'll define some models that use these channels.

```yaml
model:
  name: Pubber
  description: Periodically publishes a message.
  behavior:
    - name: send_message
      type: TIMER
      description:  Publishes an message.
      output:
        - name: response
          channel: Messages
          description: A randomly generated message.
      acceptance:
        - scenario: Normal operations
          given:
            - The service is running.
          when:
            - The timer goes off.
          then:
            - A message is generated and published to General with random content.
  state:
    - name: Counts
      type: Counters
      channel: Message_Counts

```

```yaml
model:
  name: Subber
  description: Listens for a message.
  behavior:
    - name: on_message
      type: PUB_SUB
      description:  Receives and logs an message.
      input:
        - name: my_message
          channel: Messages
          description: A randomly generated message.
      acceptance:
        - scenario: Normal operations
          given:
            - The service is running.
          when:
            - A message is received on the General channel.
          then:
            - The message content is logged to the console.
  state:
    - name: Counts
      type: Counters
      channel: Message_Counts
```

You can see how channels define explicit communication links between models.  They may also explicitly define the interaction type (i.e. pub-sub, shared-state, etc.) which could be used for additional validation to ensure proper usage.

## Future Capability

I can imagine a scenario where models could define filters against channels.  If there's a model that wants to subscribe to a channel but only cares about data with some specific value in a field, the filter would allow the modeler to describe this behavior.

I can also imagine channels that provide specific communication models.  In the example I show a pub-sub channel which would provide a published message to all subscribers.  Perhaps we would support alternatives such as round-robin queues where only one subscriber gets a particular message.  This would be a valuable way to model traditional workflow systems.

**Comment by jondavid-black** [comment]
Alex had a good comment on how we use channels in state.  The channel would provide access to data and basic CRUD (create, read, update, delete) capability.  In certain instances, we may want to model certain constraints such as defining some models as read only on the channel.  Here's an example of what that may look like.

```yaml
model:
  name: Subber
  description: Listens for a message.
  behavior:
    - name: on_message
      type: PUB_SUB
      description:  Receives and logs an message.
      input:
        - name: my_message
          channel: Messages
          description: A randomly generated message.
      acceptance:
        - scenario: Normal operations
          given:
            - The service is running.
          when:
            - A message is received on the General channel.
          then:
            - The message content is logged to the console.
  state:
    - name: Counts
      type: Counters
      channel: Message_Counts
      constraints:
        - no_create
        - no_update
        - no_delete
```
