### DISCUSSION TITLE
Cloud Modeling in AaC

### DISCUSSION THREAD

**Discussion by jondavid-black** [DevOps-MBSE/AaC#654] [Ideas]
It's easy to say, "we're using the cloud", but the reality is setting up a cloud environment that meets performance and security requirements can be challenging.  We often see this modeled as a "magic cloud" with stuff in it.  Teams who are actually responsible to design, deployment, and operation of cloud environments know this dramatically oversimplifies how the cloud works.

It would be valuable to enable some core provider-agnostic cloud and Kubernetes modeling of platforms into which systems will be deployed.  Core elements like accounts, VPCs, subnets, storage, VMs, DBs, and clusters should be available for modeling.  It would also be great to provide some distribution-agnostic Kubernetes modeling capability.  We should want to be able to model the critical design components of a Kubernetes cluster...particularly anything that would be relevant within a security audit.  That said, I think we should start as simply as possible by just including basic namespaces, containers / pods, storage, network, configuration, and secrets.  Ideally, we would be able to link a container definition to a model describing the application behavior.  We can incrementally expand this over time and prioritize things by need.  It will be helpful to enable modeling of Kubernetes services (i.e., EKS, AKS) as well as self-hosted solutions.

It would be very valuable to be able to generate cloud and Kubernetes diagrams from the model.  There is an interesting python tool called [Diagrams](https://diagrams.mingrammer.com/) that could be useful, but I'm sure there are others that may be simpler to use.  Diagrams is just nice because it has most of the cloud and Kubernetes icons already built in.

If possible, it would be ideal to generate IaC code that creates the modeled cloud platform.  This would probably not be something that could be reasonably done in a generic manner.  Each team or organization will likely have unique guidelines and constraints that must be applied.  That said, a somewhat generic generator could probably be made that at least produces stubs for the IaC content and enables down-stream engineers to populate their unique configurations.

It isn't clear to me yet what an example cloud model would look like.  I'll work to think up a simple example and add it to the discussion.

**Comment by jondavid-black** [comment]
I came across an interesting new way to define cloud resources that could be useful:  https://www.winglang.io/

**Comment by jondavid-black** [comment]
After some thought and inspiration from winglang, I believe I've got a recommendation for cloud modeling.  The key realization was to stop thinking about modeling cloud implementation and model cloud structure and behavior.  While implementation is important, we would likely want to put any implementation details into templates / logic used within a generate command rather than the declarative model itself.  That said, I can imagine a cloud deployment declaration that could augment the declarative model of the cloud structure and behavior.

A cloud model would focus on being simple enough that people who don't really understand the nuts and bolts of cloud to declare the architecture they're interested in achieving.  The cloud model should also be sufficiently abstract to enable use of various cloud service providers.  The schemas should be as simple as possible.

Schemas:
- Cloud:  An abstract container indicating a cloud target environment.   In practice this may equate to a VPC.
- VM:  A high level way to represent a virtual machine.  Probably just allows for a type, an OS, and roles to be defined.
- Bucket:  A way to store arbitrary files.
- Cluster:  A generic representation of a Kubernetes cluster.  Allows modeler to define min / max node sizes and a list of containers.  At least initially, I'm thinking we just define services rather than explicit pods/services to keep things as simple as possible.
- Service:  An application to run in the cloud or cluster.  Likely references a model which defines the application.  May also be valuable to just reference a container ID to enable modeling of COTS products in the cluster.
- Function:  Represents a serverless function.  Likely references a behavior which defined the function (enabled by #664 ).
- Topic:  A pub-sub component allowing subscriptions for data broadcast to all subscribers.  Likely references a channel model (#653 ) and a behavior.
- Queue: A data queue providing pub-sub message distribution but to a single subscriber rather than broadcast to all subscribers.  This enables an alternative data sharing architecture such as workflows and provides different means of horizontal scaling.  Likely references a channel model (#653 ) and a behavior.
- Database: A RDBMS within the cloud.  May include table definitions which reference schemas and relational keys.
- Datastore:  A shared data store, perhaps similar to Redis.  Likely references schemas to be stored and a channel model (#653 ) if the store is to be shared amongst different model components.
- Schedule:  A resource used to trigger events based on time intervals.  Likely references a function or behavior to invoke periodically.
- REST:  A way to declare a restful API.  Fields would include entries for GET, POST, etc and would reference behaviors.

Potential schemas to discuss:
- Secret:  Defines a secret such as an API-key that may need to be distributed to cloud resources.
- Env:  Defines environment variables that may need to be distributed to cloud resources.
- UUID:  Defines a universally unique ID service that can be used across the cloud.  But this may be better provided via a REST declaration.
- Counter:  Defines a counter that can be incremented, decremented, read, and reset.  Likely used for telemetry, but not constrained to just that use case.
- Log: Defines a common logging construct for use by cloud services.  In practice this would represent something like ELK, Splunk, or Grafana stack.
- Integration:  It may be valuable to model integrations amongst services.  For instance if there is a centralized authentication service, we may want to explicitly model the fact that services integrate with that for their authentication.  A potential downside is this may create confusion if the modeler believes they should create integration declarations for all the various service interactions.  Each integration may also be application specific in such a way that each integration definition may not provide much value.  If I run Jira and Confluence, should I define an integration that shows the integration between them?  Perhaps just defining a named channel (#653 ) that shows communication supporting the integration is sufficient and less prone to confusion.

It may be valuable to allow the modeler to declare various cloud resources as public or private, accessible from outside the cloud boundary or not.  We need to think about how we define RBAC as well.  If we create a VM, it is just accessible or is it locked down?  Should the VM include details such as whether or not SSH is externally available?  I think RBAC is incredibly important, but may also be incredibly complex.  We should give it some time for thought and maybe we can discover a simple RBAC modeling approach.

**Comment by jondavid-black** [comment]
Here's an example cloud model for an overly simplified SW factory.  It starts by defining a cloud environment with various cloud resources.  Each resource is then defined based on its type.  In my mind, this is an opportunity to leverage inheritance in the model with an abstrate Cloud_Resource that is the parent of VM, Bucket, Cluster, etc.  The cluster is then defined to contain services which reference specific container definitions.  Containers simply reference the repo, image, and tag to use...keeping things simple but explicit.

I've included a concept of roles in the VM and container model to reference something like Ansible roles which would apply things like security configurations or organization specific configurations.  Including roles in the model allows for a simple way to show and validate how these are applied across a system declaration.  For now I'm thinking these just reference a named role, but perhaps a more explicit role declaration approach would be valuable.

```yaml
cloud:
  name: Software_Factory
  description: A collection of tools to support software system development and delivery.
  resources:
    - Bastion
    - Log_Store
    - Factory_Cluster
```

```yaml
vm:
  name: Bastion
  description:  Administrator resource for ssh access into the cloud environment.
  config: X86_64_Large
  image: RHEL_8.8.0
  roles:
    - Config_A
    - Config_B
```

```yaml
bucket:
  name: Log_Store
  description: Storage for log data.
```

```yaml
cluster:
  name: Factory_Cluster
  description: Kubernetes cluster to host SW Factory services.
  nodes:
    min: 5
    max: 10
  services:
    - GitLab
    - Nexus
    - SonarQube
```

```yaml
service:
  name: GitLab
  description: Software version control and CI/CD
  container: 
    registry: https://registry.hub.docker.com
    image: gitlab/gitlab-ce
    tag: 16.3.2-ce.0
  roles:
    - Config_A
```

```yaml
service:
  name: Nexus
  description: Artifact CM version control.
  container: 
    registry: https://registry.hub.docker.com
    image: sonatype/nexus3
    tag: 3.59.0
  roles:
    - Config_A
```

```yaml
service:
  name: SonarQube
  description: Automated software QA.
  container: 
    registry: https://registry.hub.docker.com
    image: sonarqube
    tag: 9.9.2-community
  roles:
    - Config_A
```
