### DISCUSSION TITLE
New keyword "uses"

### DISCUSSION THREAD

**Discussion by jondavid-black** [DevOps-MBSE/AaC#670] [Ideas]
As I've been working on the first 3rd party plugin, I've realized that a user who clones a repo containing a model that uses the 3rd party plugin may not realize they need to install it.  This could create confusion.  I don't like the premise of requiring inherent user knowledge of what plugins may or may not be needed to utilize a defined model.  As such, I recommend we make it explicit by implementing the ```uses``` keyword.

The ```uses``` keyword would be declared exactly like the ```import``` keyword, but would reference the name of any plugin dependency.  When AaC runs on a model, it would parse the plugin names provided by ```uses``` and confirm the plugins are installed.  If they are not installed, then write a clean error message stating something like ```This model requires the aac-xyz plugin.  Install the AaC plugin by running `pip install aac-xyz`."

The ```uses``` keyword would be defined in the core spec as:
```yaml
schema:
  name: Uses
  fields:
    - name: plugins
      type: string[]
  validation:
    - name: Required fields are present
      arguments:
        - plugins
```

While we could include certain complexities such as defining the pypi repo URL and such, I'd advocate we apply the YAGNI principle and hold off on such things until we encounter a real-world situation that demands the additional complexity.  [You Aint Gonna Need It]

**Comment by jondavid-black** [comment]
I realize there are a few challenges and opportunities here...

Opportunities:
1. Eliminate need for plugin manager:  By explicitly declaring the used plugins we should be able to dynamically activate what is needed and deactivate what is not.
2. Validator suppression:  Maybe this is a separate thought, but if we create a good uses definition capable of clear plugin definition we could create an optional ability to suppress various validators using the same schema.

Challenges:
1. Plugins are small:  We currently define plugins to be relatively small in scale...which is good...but if we setup ```uses``` to operate at the "plugin name" level we'll have to make a lot of ```uses``` declarations.  This could be a burden for users.  I suggest we consider a higher level construct associated with the pypi name.  I like this because I think it creates clarity by aligning ```uses aac-cloud``` with ```pip install aac-cloud```.   We'd need to decide if there's value in going deeper.

**Reply by lizzcondrey** [reply]
On the opportunities piece for each item.
1. Would that mean rather than when you run `pip install aac` and that `activate`s all the plugins packaged with aac, we would do a check for `uses` within the model you are trying to build, evaluate, or use with aac and activate only those necessary out of the installed aac package?
2. Similar to above, that rather than activating all of the validator plugins as part of the `pip install aac`, we would check the `uses` for necessary validators and only `activate` those?

So, how `import` allows for cross use of definitions, `uses` would allow for cross use of entire plugins, including all definitions and validators, right? 

Using our lovely `alarm_clock` example.  Meaning `uses` would look something like this? 
```yaml
import:
  files:
    - ./structures.yaml
    - ../alarm_clock/structures.yaml
---
uses:
  plugins: 
    - Generate PlantUML Diagrams
    - Generate Gherkin Feature Files
    - Primitive Type Checking
    - Validate usecase participants
    - etc.
---
model:
  name: AlarmClock
  description: A simple alarm clock
```

Which also then hits your challenges section of scoping to "plugin name" means you'd have a lengthy list in the uses. But while the proposal of using the pypi package level does help keep that list shorter for 3rd party plugins, not sure how it assists with the 1st bullet for opportunities because then you would by default install and activate all plugins and validators with `pip install aac` still? 

So, because of that perceived conflict, I feel like I am misunderstanding something.
