### DISCUSSION TITLE
Potential new validator type of context validators?

### DISCUSSION THREAD

**Discussion by lizzcondrey** [DevOps-MBSE/AaC#681] [Ideas]
As the team has spent more time thinking about validators of late and they have come under a different angle of evaluation with a real attempt at third party plugin development, the potential need for a new validator type has been identified.

Currently, it is thought to be necessary to add a context validator type that would provide an additional bucket for validator behaviors to help keep them distinct. And potentially help with documentation and communication around validators, their roles, responsibilities, and behaviors. 

This discussion thread will serve as a catch spot for thoughts around this topic as well as a space for providing any evidence/research material to assist with implementing an additional validator type. 

Currently AaC handles [definition validations](https://arch-as-code.org/project_documentation/dev_guide/validation_plugins.html#definition-validations) and [primitive validations](https://arch-as-code.org/project_documentation/dev_guide/validation_plugins.html#primitive-validations).

**Comment by jondavid-black** [comment]
I may be thinking the same way, but using different terms.  I currently envision 2 kinds (aka categories as you say) of validators:
- Global:  These are validators that "just apply everywhere".  These would be things like `unique names` or `root keys` in the current validator definitions.  Nobody should have to figure out how to link them up with a particular schema definition, they're just everywhere and apply to everything.  These would fundamentally invert the validation logic, looping through each global validator and applying it to every definition.
- Local:  These are validators that are specific to some model construct or usage.  These would be things like `required_fields` or `exclusive_fields` in the current validator definitions.  These are specific to a defined schema type and are not relevant elsewhere.  These would keep a similar execution flow as currently in place, looping through definitions and only applying the explicitly defined validators within the defining schema.

Because there is not way to segregate these two types of validator behavior, our Validator 2.0 behavior does a traversal of definitions to collect applicable validators.  IMHO this is complex and messy...and has certainly create a lot of unexpected work for me recently trying to preserve that behavior in the core validation logic or work around it in validator definition and utilization.  This also results in a boat load of validator runs being performed for all potential permutations, with frequent duplication of validator execution and runtime performance hits.  I recently did a test where I counted the number of times validators were run in a unit test and found that if I constrained them to only run once the validator execution counts were reduced by a factor of 8.  Runtime went from ~7 sec to <1 sec.  Of course, that was for a unique validator and making that change currently pretty much breaks validation everywhere else.

I'm wondering if there's a simplified way that may lead us down a Validator 3.0 path.  To truly get our heads around what makes sense we should catalog what we've got today (and what we expect in the near-term based on our backlog) against their intended usage and applicability.  Things like `lang.hierarchy.get_definition_ancestry` could potentially go away.  The concept of `target_schema`definition` in the validator could also go away for the global instances.

We could potentially accomplish this through a tweak to the validator schema:

```yaml
enum:
  name: ValidatorType
  values:
    - GLOBAL
    - LOCAL
---
schema:
  name: Validation
  root: validation
  fields:
    - name: name
      type: string
      description: |
        The name of the validation rule and plugin.
    - name: validator_type
      type: ValidatorType
      description: Defines the execution strategy for the validator.
    - name: description
      type: string
      description: |
        A high-level description of the validation plugin.
    - name: behavior
      type: Behavior[]
      description: |
        A list of behaviors that the validation plugin will perform.
  validation:
    - name: Validation definition has an implementation
    - name: Required fields are present
      arguments:
        - name
        - description
        - validator_type
        - behavior
```

An example would look something like:

```yaml
validation:
  name: Root key is defined
  validator_type: GLOBAL
  description: Verify that the definition's root key is defined.
  behavior:
    - name: Verify that the definition's root key is defined.
      type: REQUEST_RESPONSE
```

BTW...I left the discussion of changing the vocabulary on this (#671) out for now.  You're welcome!  :)
