### DISCUSSION TITLE
is_required Alterations

### DISCUSSION THREAD

**Discussion by lizzcondrey** [DevOps-MBSE/AaC#984] [General]
Because of how the aac system is laid out, all user defined definitions that are not a concrete object (i.e. are recipes instead of finished dishes) should use the Schema root type.
Because of this, I think that the schema definition should be more flexible in how it is implemented.  I think it should have no required fields so that using the schema root does not restrict the user in the creation of their custom types.

Example: (I made myself hungry writing this, I apologize)
```
schema:
    name: Recipe
    package: recipes
    fields:
        - name: name
          type: str
        - name: ingredients
          type: str[]
    
schema:
    name: Chicken Recipe
    package: recipe
    extends:
        - name: Recipe
          package: recipe
    fields:
        - name: chicken seasoning
          type: str[]

schema:
    name: Stew
    package: recipe
    extends:
        - name: Recipe
          package: recipe

Chicken Recipe:
    name: Chicken Parmesan
    ingredients: parmesan cheese, tomato sauce
    chicken seasoning: salt, pepper, paprika, garlic powder, onion powder, basil

Stew:
    name: Beef Stew
    ingredients: beef, broccoli, potato, carrots, broth
```

Also, I think that is_required should carry over through extensions.  For example, AaCType has description as a required field, and Schema extends AaCType.  
You can include a description field in Schema, but it is not required despite it being defined as being required.

Here is also a list of every instance of is_required appearing in aac.aac:
Definition | field
---------- | ------
ModelComponent | name, model
Behavior | name
Feature | name, scenarios
Background | given, NOT name for this one?
Scenario | name, when, then
Example | name, values
ExampleValue | name, value
ContextConstraint | name
SchemaConstraint | name
PrimitiveConstraint | name
SchemaConstraintAssignment | name
PrimitiveConstraintAssignment | name
UsecaseActor | name
Usecase | name
UsecaseStep | name
UsecaseBranch | condition, steps
