### ISSUE TITLE
💭 [REQUEST] - Explicit Primitive Definition

### ISSUE THREAD

**Issue by jondavid-black** [DevOps-MBSE/AaC#675]
### Reference Issues

#652 

### Summary

Once of the concepts put forward in the discussion on inheritance was to refactor how we define and maintain primitives.

We currently use a "magic enum" to define our primitives.  This change would make primitive declaration explicit and potentially simplify primitive validation.

### Basic Example

```yaml
primitive:
  name: int
  description: Defines the int primitive type, a numerical whole-number value
  validations:
    - Integer is whole number
---
primitive:
  name: date
  description: Defines the date primitive type, an ISO 8601 compliant time stamp
  validations:
    - Date is ISO 8601 compliant
```

### What are the drawbacks/impacts of your feature request?

The only drawback known at this time is that modifying something as fundamental as primitive definition and handling could require significant work and require touchpoints throughout the baseline.  We won't have a quantification of the work required until we do some initial experimentation.  Hopefully the ```get_primitives_definition``` already used within ```language_context``` will give us a simple area of focus to work from.

### Unresolved questions

Would it be reasonable to simply treat a defined primitive like any other named type rather than something "special"?
