### ISSUE TITLE
💭 [REQUEST] - Remove Root

### ISSUE THREAD

**Issue by jondavid-black** [DevOps-MBSE/AaC#676]
### Reference Issues

#652 

### Summary

As we contemplated our strategies for inheritance, the way in which we utilize ```root``` was raised as a challenge.  Today we have a "magic type" called root which nobody should ever actually use, but constrains the tags available to use in the initial entry of your aac model. 

This change would transition the declaration of the root key for a type to the type definition itself.  This would allow us to remove the ```root``` schema all together.  The concept of root types would still exist but would be derived by the aac language from the schema definitions in the ```language_context```.

Providing a root key should be optional.  If for some reason we don't want a type to be definable as a root item, simply don't populate the defining field in the schema.

### Basic Example

As an example, let's just take the first two entries in the existing ```root``` schema and see what they would look like under this new approach.

```yaml
schema:
  name: Import
  root_key: import
  fields:
    - name: files
      type: file[]
  validation:
    - name: Required fields are present
      arguments:
        - files
```

```yaml
schema:
  name: Enum
  root_key: enum
  fields:
    - name: name
      type: string
      description: |
        The name of the enumeration.
    - name: values
      type: string[]
      description: |
        A list of strings that encompass the enumeration's possible values.
  validation:
    - name: Required fields are present
      arguments:
        - name
        - values
```

### What are the drawbacks/impacts of your feature request?

None known at the time.  In principle this should be a relatively straight-forward modification...assuming the code base consistently leverages the ```language_context``` methods related to root items: ```get_root_keys()```, ```get_root_fields()```, and ```get_root_keys_definition()```.

### Unresolved questions

Should we constrain the root key value (i.e. no white spaces, numbers, or special characters other than '-' or '_')?
