### ISSUE TITLE
🐛 [BUG] - Root Key Rename LSP

### ISSUE THREAD

**Issue by Coffee2Bits** [DevOps-MBSE/AaC#685]
### Pre-requisites

- [X] I checked the documentation and found no answer.
- [X] I checked to make sure that this issue has not already been filed.

### What version of the AaC package are you using? Check your version with the command: aac version.

0.3.0

### Description

The LSP feature to rename root keys does not work with the new 0.3.0 update. 

The expected functionality is that when a user selects `rename symbol` on a root key that's not defined in a protected file (core spec or plugin-provided file), then the new `root` field of the key-defining schema and all instances of the root key are updated to the new value.
![Screenshot 2023-09-16 at 3 01 26 AM](https://github.com/DevOps-MBSE/AaC/assets/60155541/28f03019-8f80-4c24-9a75-3eb0aeb492a7)

Using the alarm clock model as an example, the expected behavior would follow like so:
```yaml
schema:
  name: TimerAlert
  root: timer_alert
  description: Data structure for timer alerts.
  fields:
    - name: name
      type: string
    - name: triggeredTime
      type: Timestamp
    - name: alarmNoise
      type: AlarmNoise
---
...
---
timer_alert:
  name: my_alert
  triggeredTime:
    hour: 06
    minute: 30
    second: 00
    year: 2022
    month: 01
    day: 01
```

If the user renamed the symbol `timer_alert` to `my_timer_alert` then the following changes would be made for the user:

```yaml
schema:
  name: TimerAlert
  root: my_timer_alert
  description: Data structure for timer alerts.
  fields:
    - name: name
      type: string
    - name: triggeredTime
      type: Timestamp
    - name: alarmNoise
      type: AlarmNoise
---
...
---
timer_alert:
  name: my_timer_alert
  triggeredTime:
    hour: 06
    minute: 30
    second: 00
    year: 2022
    month: 01
    day: 01
```

### Reproduction steps

```bash
Please enter an explicit description of your issue
1. Open the alarm clock model with the 0.3.0 LSP
2. Select the `timer_alert` root key or `root` field value `timer_alert`
3. Right-click and select the `rename symbol` option
4. Enter the new value `my_timer_alert`
```

### Screenshots

```bash
Included in description
```

### Logs

```bash
N/A
```

### Pertinent Files

N/A
