### ISSUE TITLE
Gen-plugin fails to generate plugins from any directory other than the project root

### ISSUE THREAD

**Issue by cvchaparro** [DevOps-MBSE/AaC#75]
When trying to generate a new plugin using the `gen-plugin` command, one must be in the top-level `aac` directory for anything to be generated.

## Steps to reproduce

1. Create a valid AaC model in a file called `aac/plugins/aac-gen-design-doc/aac-gen-design-doc.yaml`:
   ```yaml
   model:
     name: aac-gen-design-doc
     description: aac-gen-design-doc is an Architecture-as-Code plugin that generates a System Design Document from Architecture-as-Code models.
     behavior:
       - name: gen-design-doc
         type: command
         description: Generate a System Design Document from Architecture-as-Code models.
         input:
           - name: architecture_files
             type: string[]
             description: The yaml files containing the modelled system for which to generate the System Design document.
           - name: output_directory
             type: string
             description: The directory to which the System Design document will be written.
         acceptance:
           - scenario: Output a System Design document containing an outline of the model and its components.
             given:
               - The {{gen-design-doc.input.architecture_files}} represent a valid system architecture.
             when:
               - The aac application is run with the gen-design-doc command and one, or more, valid architecture files.
             then:
               - A System Design document is written to {{gen-protobuf.input.output_directory}}.
               - The System Design document contains an outline based on the structure of the given model.
           - scenario: Output a System Design document containing use cases and their descriptions.
             given:
               - The {{gen-design-doc.input.architecture_files}} represent a valid system architecture.
             when:
               - The aac application is run with the gen-design-doc command and one, or more, valid architecture files.
             then:
               - A System Design document is written to {{gen-protobuf.input.output_directory}}.
               - The System Design document contains a headers with use cases names.
               - The System Design document contains content with use cases descriptions under the headers.
   ```
1. Run the `gen-plugin` command from the `aac/plugins/aac-gen-design-doc/` directory:
   ```bash
   (.env) $ cd plugins/aac-gen-design-doc/
   (.env) $ aac gen-plugin aac-gen-design-doc.yaml
   ```
1. Enter `y` when prompted if you want to generate the plugin files in the `aac-gen-design-doc/` directory.
1. View the contents of the `aac-gen-design-doc/` directory:
   ```bash
   (.env) $ tree .
   .
   └── aac-gen-design-doc.yaml

   0 directories, 1 file
   ```

## Expected Behavior

Running the `gen-plugin` command should generate files in the specified directory regardless of where the command is run from.

## Current Workaround

Run the `gen-plugin` command from the top-level `aac/` directory.
